type: AmqpCliConfig
spec:
    connection: 
      container: "amqp://10.110.191.161"
      authentication:
        type: ConnSASLPlain
        username: user1
        password: password
    sessions:
    - links:
      - role: receiver
        initialCredit: 10
        source: "myqueue"
